import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

import StoreProvider from "@/redux/StoreProvider";

export const metadata: Metadata = {
  title: "FloZap",
  description: "Generated by create next app",
  icons: {
  icon: '/icon.png',
  shortcut: '/icon.png',
  apple: '/icon.png',
}
};
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
