import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

import StoreProvider from "@/redux/StoreProvider";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "FloZap",
  description: "Generated by create next app",
  icons: {
  icon: '/icon.png',
  shortcut: '/icon.png',
  apple: '/icon.png',
}
};
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <StoreProvider>
          {children}
        </StoreProvider>
        <Link
          className="fixed bottom-2 right-2 z-50 bg-white p-2 rounded-full shadow-lg hover:shadow-xl transition animate-bounce duration-500"
          target="_blank"
          href="https://t.me/flozap"
        >
          <Image
            src="/Telegram_logo.svg"
            alt="Telegram Logo"
            width={30}
            height={30}
          />
        </Link>
      </body>
    </html>
  );
}

